services:
  - type: web
    name: riat-blog-jiten
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: GENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
